name: Deploy Next.js statically built site to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    env:
      NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: my-app

      - name: Build with Next.js
        run: npm run build
        working-directory: my-app

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload statically built files for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-app/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4